services:
  python-django:
    image: 3-1/python-django
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ../.env.local
    networks:
      - waect-network

networks:
  waect-network:
    external: true
