version: "3"

services:
  gh-actions-python-tests:
    image: gh-actions-python-tests
    build: .
    container_name: gh-actions-python-tests
    volumes:
      - ../..:/workspaces:cached
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres-gh-actions-python-tests:5432/postgres
      - MINITWIT_URL=http://minitwit-python-flask:5000

  minitwit-python-flask:
    image: minitwit-python-flask
    build: 
      context: ../../python-flask/
      dockerfile: ./Dockerfile
    container_name: minitwit-python-flask
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres-gh-actions-python-tests:5432/postgres
      - SECRET_KEY=waectsk
    ports:
      - 5000:5000

  postgres-gh-actions-python-tests:
    image: postgres:17
    container_name: postgres-gh-actions-python-tests
    hostname: postgres-gh-actions-python-tests
    environment:
      - POSTGRES_PASSWORD=1234 
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ../../database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
