FROM mcr.microsoft.com/devcontainers/base:jammy

WORKDIR /app

# Update package lists and install dependencies in a single RUN command
RUN apt-get update \
    && apt install \
        python3 \
        python3-pip \
        libpq-dev \
        golang \
        -y \
    && rm -rf /var/lib/apt/lists/*

# Install node
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash \
    && \. "$HOME/.nvm/nvm.sh" \
    && nvm install 22

# Install .NET SDK
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && sudo dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb

RUN apt-get update \ 
    && apt-get install -y dotnet-sdk-8.0

# Install Java and Maven packages
RUN apt-get update && apt-get install -y openjdk-17-jdk
RUN apt-get update && apt-get install -y maven
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"
WORKDIR /app/java_spring/MiniTwit
# RUN mvn clean install -U

WORKDIR /app
# Keep container running (for debugging)
CMD sleep infinity
