services:
  rust-actix:
    image: rust-actix
    container_name: rust-actix
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file:
      - ../.env.local
    networks:
      - waect-network

networks:
  waect-network:
    external: true
