services:
  python-flask:
    image: waect/python-flask
    build: .
    ports:
      - "5022:5022"
    env_file:
      - ../.env.local
    networks:
      - waect-network

networks:
  waect-network:
    external: true