services:
  python-flask:
    image: waect/python-flask
    build: .
    container_name: python-flask
    env_file:
      - ../.env.local
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - waect-network

networks:
  waect-network:
    name: waect-network
    driver: bridge
    external: true