services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - waect-network

networks:
  waect-network:
    name: waect-network
    driver: bridge
    external: true