services:
  # SH to test the connection to the database
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: waect
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      DB_HOST: host.docker.internals
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - waect-network
    
networks:
  waect-network:
    name: waect-network
    driver: bridge
