services:
  local_database:
    image: postgres:latest
    container_name: local_postgres
    environment:
      POSTGRES_DB: waect
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      DB_HOST: host.docker.internals
      DB_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - waect-network

networks:
  waect-network:
    name: waect-network
    driver: bridge

volumes:
  postgres_data:
