services:
  go-gorilla:
    image: waect/go-gorilla:latest
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ../.env.local
    networks:
      - waect-network

networks:
  waect-network:
    external: true
  
