services:
  go-gorilla:
    build:
      context: ../Gorilla/minitwit-web-app
      dockerfile: Dockerfile
    container_name: go-gorilla-web-app
    ports:
      - "15000:15000"
    depends_on:
      - local_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PW: pass
      POSTGRES_HOST: local_postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: waect
      POSTGRES_DISABLE_SSL: true
    networks:
      - waect-network

networks:
  waect-network:
    external: true