---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
  # allow manual triggers for now too
  workflow_dispatch:
    manual: true

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD
# SSH_USER
# SSH_KEY
# SSH_HOST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push minitwitimage
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:src"
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwitimage:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitimage:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitimage:webbuildcache,mode=max

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY"
          echo "$SSH_KEY" > ~/.ssh/do_ssh_key.key
          chmod 600 ~/.ssh/do_ssh_key.key

          ssh-keyscan 46.101.250.219 >> ~/.ssh/known_hosts
          cat >> ~/.ssh/config <<END
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            LogLevel ERROR
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Remove old deployment tools
        run: ssh root@46.101.250.219 -i ~/.ssh/do_ssh_key.key 'rm -rf /vagrant/tools/*'
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Copy deployment tools to server
        run: rsync -Pav -e "ssh -i ~/.ssh/do_ssh_key.key" --no-perms --no-owner --no-group tools/* root@46.101.250.219:/vagrant/tools/
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Deploy to server
        run: ssh root@46.101.250.219 -i ~/.ssh/do_ssh_key.key 'chmod 777 /vagrant/tools/* && /vagrant/tools/deploy.sh'
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

  release:
    needs: "build"
    permissions: write-all
    name: "Automatic release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automatic latest release"
