
name: Build and Push Docker Image WEAC Codebase

on:
  push:
    branches:
      - feat/cd-build-push
    paths:
      - 'python-flask/**'
      - 'c-sharp-razor/**'
      - 'rust-actix/**'
      - 'ruby-sinatra/**'
      - 'javascript-express/**'
      - 'go-gin/**'
      - 'go-gorilla/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - python-flask
          - c-sharp-razor
          - rust-actix
          - ruby-sinatra
          - javascript-express
          - go-gin
          - go-gorilla

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine if Service Needs Build
        id: check_changes
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            if git diff --name-only HEAD^ HEAD | grep -q "^${{ matrix.service }}/"; then
              echo "service_changed=true" >> $GITHUB_ENV
            else
              echo "service_changed=false" >> $GITHUB_ENV
            fi
          else
            echo "No previous commit found, skipping check."
            echo "service_changed=true" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        if: env.service_changed == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        if: env.service_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if Dockerfile exists
        if: env.service_changed == 'true'
        id: check_file
        run: |
          if [ -d "./${{ matrix.service }}" ] && [ -f "./${{ matrix.service }}/docker-compose.yml" ]; then
            echo "found=true" >> $GITHUB_ENV
          else
            echo "found=false" >> $GITHUB_ENV
          fi

      - name: Install Docker Compose
        if: env.found == 'true'
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Build and Push Docker Image
        if: env.found == 'true'
        run: |
          cd ${{ matrix.service }}
          docker-compose build
          COMMIT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          docker tag ${{ matrix.service }}_web:latest simonharwick97822/${{ matrix.service }}:latest
          docker tag ${{ matrix.service }}_web:latest simonharwick97822/${{ matrix.service }}:commit-sha-${COMMIT_SHA}-${TIMESTAMP}

      - name: Push Docker Image
        if: env.found == 'true'
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          docker push simonharwick97822/${{ matrix.service }}:latest
          docker push simonharwick97822/${{ matrix.service }}:pr-$commit-sha-${COMMIT_SHA}-${TIMESTAMP}
