
name: Build and Push Docker Image WEAC Codebase

on:
  push:
    branches:
      - cd-build-push
    paths:
      - 'python-flask/**'
      - 'c-sharp-razor/**'
      - 'rust-actix/**'
      - 'ruby-sinatra/**'
      - 'javascript-express/**'
      - 'go-gin/**'
      - 'go-gorilla/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - python-flask
          - c-sharp-razor
          - rust-actix
          - ruby-sinatra
          - javascript-express
          - go-gin
          - go-gorilla

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine if Service Needs Build
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^${{ matrix.service }}/"; then
            echo "service_changed=true" >> $GITHUB_ENV
          else
            echo "service_changed=false" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        if: env.service_changed == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        if: env.service_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # github username
          password: ${{ secrets.DOCKER_PASSWORD }} # github password

      - name: Check if Dockerfile exists
        if: env.service_changed == 'true'
        id: check_file
        run: |
          if [ -d "./${{ matrix.service }}" ] && [ -f "./${{ matrix.service }}/docker-compose.yml" ]; then
            echo "found=true" >> $GITHUB_ENV
          else
            echo "found=false" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        if: env.found == 'true'
        run: |
          cd ${{ matrix.service }}
          docker-compose build
          docker tag ${{ matrix.service }}_app: latest simonharwick97822/${{ matrix.service }}_app:latest

      - name: Push Docker Image
        if: env.found == 'true'
        run: |
          docker push simonharwick97822/${{ matrix.service }}_app:latest
