name: Push Client Container Image to GitHub Container Registry

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
        paths:
            - frontend-experiment/postgres/**
    
    push:
        branches:
            - main
        paths:
            - frontend-experiment/postgres/**

    workflow_dispatch:


env:
    REGISTRY: ghcr.io
    IMAGE_NAME: 3-1-research-project/client
    DOCKERFILE_PATH: frontend-experiment/client/

jobs:
    build-and-publish-image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract Python version
              id: extract-version
              run: |
                PYTHON_VERSION=$(grep -oP '(?<=FROM python:)\d+' ${{ env.DOCKERFILE_PATH }}dockerfile)
                echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

            - name: Build container image
              if: github.event_name == 'pull_request'
              id: build
              uses: docker/build-push-action@v3
              with:
                context: ${{ env.DOCKERFILE_PATH }}
                push: false
                platforms: linux/amd64,linux/arm64  

            - name: Log in to the Container registry
              if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
              uses: docker/login-action@v2
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.PAT }}

            - name: Extract metadata (tags, labels) for Docker
              if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
              id: meta
              uses: docker/metadata-action@v3
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                  ${{ env.PYTHON_VERSION }}

            - name: Push container image
              if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
              id: push
              uses: docker/build-push-action@v3
              with:
                context: ${{ env.DOCKERFILE_PATH }}
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
